/**
 * Every user-facing string lives here (A5). No user-facing literals inline in
 * components or tools. Interpolated strings are functions.
 */
export const STRINGS = {
  app: {
    name: 'Apollo',
    tray: { open: 'Open Apollo', quickCapture: 'Quick capture', palette: 'Command palette', settings: 'Settings…', mute: 'Mute microphone', unmute: 'Unmute microphone', quit: 'Quit Apollo' },
    palettePlaceholder: 'Ask Apollo…',
  },

  errors: {
    KEY_MISSING: (provider: string) => `There's a problem with your ${provider} key. Check Settings > Keys.`,
    KEY_INVALID: (provider: string) => `There's a problem with your ${provider} key. Check Settings > Keys.`,
    RATE_LIMITED: "That service is busy right now. I'll be ready to retry in a moment.",
    OFFLINE: (unavailable: string, works: string) => `I'm offline, so I can't fetch ${unavailable}. ${works} still works.`,
    STT_DOWN: 'My hearing is acting up. You can keep typing to me.',
    TTS_DOWN: "I lost my voice for a moment; I'll answer as text and cards until it's back.",
    LLM_DOWN: "My brain's connection is down. Timers, notes, and your calendar still work locally.",
    TOOL_FAIL: (doing: string) => `I hit a snag while ${doing}. Want me to try again?`,
    TIMEOUT: 'That was taking too long, so I stopped it.',
    CANCELED: '',
    INTERNAL: 'Something went wrong on my end. Mind trying that again?',
    THROTTLED: 'That was too many requests at once. Give me a second.',
    REAUTH_NEEDED: 'I need you to reconnect your Google account in Settings > Accounts.',
    DB_CORRUPT: 'Your data file was damaged. I restored your most recent backup and kept the damaged copy aside.',
  },

  confirm: {
    ask: (summary: string) => `${summary} — should I?`,
    askShort: 'Send it?',
    approve: 'Approve',
    deny: 'Deny',
    canceled: 'Canceled.',
    denied: "Okay, I won't.",
    expired: 'That confirmation expired, so I did nothing.',
    superseded: 'Replaced by a newer request.',
    cancelWindow: (s: number) => `Sending in ${s}…`,
    cancelNow: 'Cancel',
    emailSummary: (to: string, subject: string) => `Send email to ${to}: "${subject}"`,
    taintWarning: (arg: string) => `The ${arg} did not come from you — double-check it.`,
  },

  cards: {
    pin: 'Pin',
    unpin: 'Unpin',
    delete: 'Delete',
    edit: 'Edit',
    cancel: 'Cancel',
    send: 'Send',
    loadImages: (n: number) => `Load images (${n})`,
    moreEvents: (n: number) => `+${n} more`,
    to: 'To',
    subject: 'Subject',
    unread: 'Unread',
    today: 'Today',
    tomorrow: 'Tomorrow',
    allDay: 'All day',
  },

  spoken: {
    timerSet: (label: string) => `Timer set for ${label}.`,
    timerDone: (label: string | null) => (label ? `Your ${label} timer is done.` : 'Your timer is done.'),
    timerCanceled: 'Timer canceled.',
    alarmFired: (label: string | null) => (label ? `Alarm: ${label}.` : "It's time."),
    reminderFired: (text: string) => `Reminder: ${text}.`,
    timeNow: (time: string) => `It's ${time}.`,
    dateToday: (date: string) => `Today is ${date}.`,
    appOpened: (app: string) => `Opening ${app}.`,
    appNotFound: (candidates: string[]) => `I couldn't find that app. Closest matches: ${candidates.join(', ')}.`,
    volumeSet: (pct: number) => `Volume ${pct} percent.`,
    muted: 'Muted. Tap the orb or press the hotkey when you need me.',
    unmuted: "I'm listening again.",
    stoppedTalking: 'Okay.',
    undone: (what: string) => `Undone: ${what}.`,
    nothingToUndo: 'There is nothing to undo in this conversation.',
    nothingToRepeat: "I haven't said anything yet.",
    newConversation: 'Starting fresh.',
    whileAway: (n: number) => `While you were away: ${n} ${n === 1 ? 'item' : 'items'}.`,
    briefIntro: 'Here is your brief.',
    weatherNow: (place: string, temp: number, condition: string) => `It's ${temp} degrees and ${condition.toLowerCase()} in ${place}.`,
    weatherForecast: (place: string, when: string, hi: number, lo: number, condition: string) =>
      `${when} in ${place}: ${condition.toLowerCase()}, high ${hi}, low ${lo}.`,
    weatherNoHome: "I don't have a home location yet. Set one in Settings, under Profile.",
  },

  onboarding: {
    welcomeTitle: 'Meet Apollo',
    welcomeBody: 'A quiet assistant that lives at the edge of your screen. Talk to it, or type.',
    permissionsTitle: 'Two permissions',
    permissionsBody: 'Apollo needs the microphone to hear you, and accessibility to see the active window. Both stay on this Mac.',
    keysTitle: 'Connect your keys',
    keysBody: 'Anthropic and Deepgram keys are required. The others unlock extras and can wait.',
    finishTitle: "You're set",
    finishBody: (hotkey: string) => `Try: press ${hotkey} and type "set a timer for 5 minutes".`,
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    done: 'Finish',
    test: 'Test',
    profileTitle: 'A little about you',
    profileBody: 'Your name is required. Location is optional, and everything is editable later in Settings — it powers weather and the daily brief.',
    profileName: 'Name (required)',
    profileNamePlaceholder: 'What should Apollo call you?',
    profileHome: 'Location (optional)',
    profileNameMissing: 'Please enter your name to continue.',
    wakeTitle: 'Hands-free',
    wakeBody: 'Say "Hey Apollo" to wake it, or hold the hotkey to talk without a wake word. Tune how sensitive the wake word is.',
    wakeToggle: 'Enable wake word',
    wakeSensitivity: 'Sensitivity',
    tryTitle: 'Try it',
    tryBody: (hotkey: string) => `Press ${hotkey}, then try "set a timer for 5 minutes" or "what's the weather".`,
    tryFinish: 'Open Apollo',
  },

  settings: {
    tabs: { profile: 'Profile', general: 'General', voice: 'Voice', proactive: 'Proactive', accounts: 'Accounts', keys: 'Keys', privacy: 'Privacy', diagnostics: 'Diagnostics', about: 'About' },
    proactive: {
      title: 'Proactive nudges',
      master: 'Let Apollo nudge me',
      maxPerDay: 'Maximum nudges per day',
      voiceOnNudges: 'Speak time-sensitive nudges',
      leadMinutes: 'Lead time (minutes)',
      digestTime: 'Time',
      staleHours: 'Stale after (hours)',
      recent: 'Recent nudges',
      noRecent: 'No nudges yet.',
      outcomeLabels: { acted: 'acted', dismissed: 'dismissed', snoozed: 'snoozed', expired: 'expired' } as Record<string, string>,
    },
    general: { launchAtLogin: 'Launch at login', hotkey: 'Global hotkey', orbEdge: 'Orb edge', homeLocation: 'Location', openWorkspaceOnLaunch: 'Open Workspace on launch', resetOrbPosition: 'Reset orb position', quickCaptureHotkey: 'Quick Capture hotkey', quickCaptureType: 'Quick Capture default' },
    profile: {
      title: 'Your profile',
      name: 'Name',
      nameRequired: 'Name (required)',
      namePlaceholder: 'What should Apollo call you?',
      location: 'Location',
      locationOptional: 'Location (optional)',
      country: 'Country',
      countryPlaceholder: 'Select a country…',
      city: 'City',
      cityPlaceholder: 'Type your city…',
      cityPickCountryFirst: 'Choose a country first',
      cityNoMatches: 'No matching cities',
      units: 'Units',
      imperial: 'Fahrenheit',
      metric: 'Celsius',
      timeFormat: 'Time format',
      h12: '12-hour',
      h24: '24-hour',
      weekStart: 'Week starts on',
      monday: 'Monday',
      sunday: 'Sunday',
      clearHome: 'Clear',
    },
    about: {
      title: 'About Apollo',
      version: (v: string) => `Version ${v}`,
      checkUpdates: 'Check for updates',
      checking: 'Checking…',
      upToDate: "You're up to date.",
      updateAvailable: (v: string) => `Update available: ${v}. It will apply on next launch.`,
      updatesDisabled: 'Updates apply to installed builds only.',
      licenses: 'Open-source licenses',
      openLogs: 'Open logs folder',
    },
    voice: {
      wake: 'Wake word', sensitivity: 'Sensitivity', ptt: 'Push to talk', voice: 'Voice', preview: 'Preview', dnd: 'Do not disturb',
      inputDevice: 'Microphone', outputDevice: 'Speaker', systemDefault: 'System default',
      ttsRate: 'Speech rate', earconVolume: 'Sound volume', followup: 'Follow-up window', off: 'Off', pauseWakeOnBattery: 'Pause wake word on battery',
    },
    accounts: { gmail: 'Gmail', connect: 'Connect', disconnect: 'Disconnect', reconnect: 'Reconnect', reauthBadge: 'Reconnect needed', connectedAs: (a: string) => `Connected as ${a}` },
    keys: {
      title: 'API keys',
      test: 'Test',
      ok: 'Key works.',
      bad: (msg: string) => `Key failed: ${msg}`,
      providers: { anthropic: 'Anthropic', deepgram: 'Deepgram', brave: 'Brave Search', picovoice: 'Picovoice' },
      configured: (last4: string, date: string) => `Configured (…${last4}) since ${date}`,
      remove: 'Remove',
      replace: 'Replace',
    },
    privacy: {
      history: 'Keep conversation history',
      historyHint: 'Turning this off also deletes indexed chats from semantic search.',
      memoryFacts: 'Remembered facts',
      egress: 'Apollo only ever talks to these hosts:',
      approvedDirs: 'Folders Apollo may search',
      wipe: 'Wipe all data',
      wipeConfirmPrompt: 'Type ERASE to delete everything.',
      wipeConfirmWord: 'ERASE',
      memoryIndex: 'Memory index',
      memoryIndexWhat: 'Apollo can search your notes, past chats, and remembered facts by meaning. Indexing happens entirely on this device; nothing is uploaded.',
      memoryIndexCounts: (note: number, message: number, fact: number, mb: string) =>
        `${note} notes, ${message} chats, ${fact} facts indexed · ${mb} MB on disk`,
      memoryIndexDisabled: 'Indexing is off. Rebuild to turn it back on.',
      memoryIndexPending: (n: number) => `${n} waiting to embed`,
      rebuildIndex: 'Rebuild index',
      clearIndex: 'Clear index',
      embedderState: (s: string) => `Embedder: ${s}`,
      data: 'Data',
      backupNow: 'Back up now',
      backups: 'Backups',
      restore: 'Restore',
      restoreConfirm: (f: string) => `Restore from ${f}? Apollo will snapshot your current data, then relaunch.`,
      export: 'Export…',
      exportWithChats: 'Include conversations',
      import: 'Import…',
      exportDone: (p: string) => `Exported to ${p}`,
      importDone: (n: number) => `Imported ${n} items.`,
      actionLog: 'Action log',
      actionLogEmpty: 'Nothing yet.',
    },
    diagnostics: { perf: 'Latency (ms)', adapters: 'Adapters', logs: 'Recent log', copy: 'Copy diagnostics', resources: 'Resources (RSS)' },
  },

  notifications: {
    whileAwayTitle: 'While you were away',
    voiceDisabled: 'Voice is disabled after repeated audio errors. Text still works.',
    updateReady: 'An update is ready. It will apply on next launch.',
  },

  fastPath: {
    unsupportedAlternative: (nearest: string) => `I can't do that yet, but I can ${nearest}.`,
  },

  nudges: {
    dismiss: 'Dismiss',
    snooze5: 'Snooze 5 min',
    openCalendar: 'Open calendar',
    openToday: 'Open today',
    openInbox: 'Open inbox',
    // rule copy (title/body builders)
    meetingLeadTitle: (title: string, mins: number) => `${title} in ${mins} min`,
    meetingLeadBody: (time: string, location: string | null) => (location ? `${time} · ${location}` : time),
    tomorrowPreviewTitle: (n: number) => `${n} events tomorrow`,
    tomorrowPreviewBody: 'Here is how tomorrow looks.',
    overdueTodosTitle: (n: number) => `${n} overdue ${n === 1 ? 'to-do' : 'to-dos'}`,
    overdueTodosBody: (items: string[]) => items.join('; '),
    needsReplyTitle: (n: number) => `${n} ${n === 1 ? 'thread needs' : 'threads need'} a reply`,
    needsReplyBody: (items: string[]) => items.join('; '),
    weatherHeadsUpTitle: 'Rain likely',
    weatherHeadsUpBody: (event: string) => `Rain likely before your ${event} — grab an umbrella?`,
    // rule names/descriptions for Settings + auto-tune
    ruleNames: {
      meeting_lead: 'meeting reminders',
      tomorrow_preview: "tomorrow's preview",
      overdue_todos: 'overdue to-do nudges',
      needs_reply: 'reply reminders',
      weather_heads_up: 'weather heads-ups',
    } as Record<string, string>,
    ruleDescriptions: {
      meeting_lead: 'A quiet heads-up a few minutes before a meeting starts.',
      tomorrow_preview: "An evening summary when tomorrow is busy or starts early.",
      overdue_todos: 'A once-a-day nudge when to-dos are more than a day overdue.',
      needs_reply: 'A daily digest of inbound email threads waiting on your reply.',
      weather_heads_up: 'A morning heads-up when rain is likely before an event with a location.',
    } as Record<string, string>,
    autoTuneQuestion: (ruleName: string) => `Want me to stop ${ruleName}?`,
    autoTuneYes: 'Yes, stop',
    autoTuneKeep: 'Keep',
    stopped: (ruleName: string) => `Okay, I'll stop ${ruleName}.`,
    // voice tool replies
    ruleDisabled: (ruleName: string) => `I've turned off ${ruleName}.`,
    ruleEnabled: (ruleName: string) => `I've turned on ${ruleName}.`,
    allDisabled: "I've turned off all proactive nudges.",
    allEnabled: "I've turned all proactive nudges back on.",
    status: (rules: string[], remaining: number) =>
      rules.length === 0
        ? `Proactive nudges are off. Budget: ${remaining} left today.`
        : `Active nudges: ${rules.join(', ')}. Budget: ${remaining} left today.`,
    quietExplanation:
      'Apollo stays quiet during your Do Not Disturb hours and fullscreen apps, caps nudges per day, and spaces them at least 20 minutes apart.',
    recentNudges: 'Recent nudges',
  },

  quickCapture: {
    placeholder: 'Capture a thought…',
    chipNote: 'Note',
    chipTodo: 'To-do',
    chipReminder: (when: string) => `Reminder · ${when}`,
    savedNote: 'note',
    savedTodo: 'to-do',
    savedReminder: 'reminder',
  },

  recall: {
    title: 'From your notes & memory',
    empty: 'No matches in your notes, chats, or memory.',
  },

  a11y: {
    voiceState: {
      idle: '', waking: 'Waking', listening: 'Listening', thinking: 'Thinking',
      speaking: 'Speaking', followup: 'Listening for a follow-up', muted: 'Muted', error: 'Voice error',
    } as Record<string, string>,
  },

  alerts: {
    timer: 'Timer',
    alarm: 'Alarm',
    dismiss: 'Dismiss',
    snoozeMin: (m: number) => `Snooze ${m}m`,
    since: (t: string) => `Ringing ${t}`,
    now: 'now',
    dndSilent: 'Silenced (Do Not Disturb).',
    ariaRinging: (label: string) => `${label} ringing`,
  },

  usage: {
    warnCard: "Heads up: today's usage passed your limit.",
    panelTitle: 'Usage',
    today: 'Today',
    month: 'This month',
  },

  permissions: {
    accessibilityHint:
      'I need Accessibility permission to see the active window. Grant it in System Settings > Privacy & Security > Accessibility, then enable Apollo.',
    micHint: 'I need microphone permission to hear you. Grant it in System Settings > Privacy & Security > Microphone.',
  },

  workspace: {
    nav: { today: 'Today', calendar: 'Calendar', notes: 'Notes', chats: 'Chats', settings: 'Settings' },
    chats: {
      filter: 'Filter conversations…',
      empty: 'No conversations yet.',
      selectHint: 'Select a conversation to read it.',
      continue: 'Continue',
      delete: 'Delete',
      deleteConfirm: 'Delete this conversation and its indexed messages?',
    },
    greeting: (name: string, partOfDay: string) => (name ? `Good ${partOfDay}, ${name}.` : `Good ${partOfDay}.`),
    today: {
      upNext: 'Up next',
      todaysEvents: "Today's schedule",
      reminders: 'Reminders',
      todos: 'To-dos',
      weather: 'Weather',
      latestBrief: 'Latest brief',
      regenerate: 'Regenerate',
      addTodo: 'Add a to-do…',
      snooze: 'Snooze',
      complete: 'Done',
      emptyUpNext: 'Nothing coming up.',
      emptyEvents: 'No events today.',
      emptyReminders: 'No reminders due.',
      emptyTodos: 'All clear.',
      emptyWeather: 'Set your home location in Settings > Profile to see weather.',
      emptyBrief: 'No brief yet. Say "good morning" or press Regenerate.',
      newEvent: 'New event',
      relMin: (m: number) => `in ${m} min`,
      relHour: (h: number) => `in ${h} h`,
      relNow: 'now',
      overdue: 'overdue',
    },
    calendar: {
      month: 'Month',
      week: 'Week',
      agenda: 'Agenda',
      today: 'Today',
      prev: 'Previous',
      next: 'Next',
      moreEvents: (n: number) => `+${n} more`,
      newEvent: 'New event',
      allDay: 'All day',
      quickCreateTitle: 'New event',
      titlePlaceholder: 'Title',
      duration: 'Duration',
      dur30: '30m',
      dur60: '1h',
      dur120: '2h',
      durAllDay: 'All day',
      create: 'Create',
      tzDiffers: (tz: string) => `in ${tz}`,
    },
    scopeDialog: {
      title: 'This is a repeating event',
      body: 'Apply your change to just this one, or all of them?',
      single: 'This event',
      all: 'All events',
      cancel: 'Cancel',
    },
    editor: {
      title: 'Event',
      titleField: 'Title',
      allDay: 'All day',
      start: 'Start',
      end: 'End',
      timezone: 'Time zone',
      recurrence: 'Repeat',
      recNone: 'None',
      recDaily: 'Daily',
      recWeekly: (weekday: string) => `Weekly on ${weekday}`,
      recWeekdays: 'Weekdays',
      recMonthly: (day: number) => `Monthly on day ${day}`,
      recCustom: 'Custom (RRULE)',
      location: 'Location',
      notes: 'Notes',
      reminder: 'Reminder (minutes before)',
      save: 'Save',
      delete: 'Delete',
      cancel: 'Cancel',
      invalidRrule: 'That recurrence rule is not valid.',
      invalidTime: 'Please enter a valid start and end time.',
    },
    notes: {
      searchPlaceholder: 'Search notes…',
      newNote: 'New note',
      pinned: 'Pinned',
      untitled: 'Untitled',
      saving: 'Saving…',
      saved: 'Saved',
      words: (n: number) => `${n} ${n === 1 ? 'word' : 'words'}`,
      pin: 'Pin',
      unpin: 'Unpin',
      delete: 'Delete',
      deletedToast: 'Note deleted.',
      undo: 'Undo',
      empty: 'No notes yet.',
      emptyEditor: 'Select a note or create a new one.',
      placeholder: 'Start writing…',
    },
    omni: {
      placeholder: 'Search notes, events, and memory…',
      notes: 'Notes',
      events: 'Events',
      facts: 'Facts',
      empty: 'No matches.',
    },
    stage: {
      morningBrief: 'Morning brief',
      weatherIn: (place: string) => `Today's weather in ${place}`,
      news: 'Latest news',
      schedule: 'Your schedule',
      openInApollo: 'Open in Apollo',
    },
    appOpened: (view: string) => `Opened ${view}.`,
  },
} as const;

export type Strings = typeof STRINGS;
